bank/Customer/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bank import app, conn, bcrypt
from bank.forms import TradeForm
from flask_login import current_user
from bank.models import select_investments, markets, execute_order



import sys, datetime

#202212
# roles is defined in the init-file
from bank import roles, mysession

iEmployee = 1
iCustomer = 2


Customer = Blueprint('Customer', __name__)


@Customer.route("/trade", methods=['GET', 'POST'])
def trade():
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))

    user_id = current_user.get_id()
    market_data = markets()

    #forms = [TradeForm(market_data[0][i]) for i in range(len(market_data))] 

    form = TradeForm()

    if form.is_submitted():
        execute_order(form,user_id)    
        

    return render_template('trade.html', title='Trade', market_data=market_data, form=form)

@Customer.route("/portfolio", methods=['GET', 'POST'])
def portfolio():

    #202212
    # Her laves et login check
    if not current_user.is_authenticated:
        flash('Please Login.','danger')
        return redirect(url_for('Login.login'))

    mysession["state"]="invest"
    print(mysession)
    user_id = current_user.get_id()
    inv = select_investments(user_id)

    
    return render_template('portfolio.html', title='Investments', inv=inv)

bank/Login/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from bank import app, conn, bcrypt
from bank.forms import CustomerLoginForm
from flask_login import login_user, current_user, logout_user, login_required
from bank.models import Investors, select_Investors


from bank import roles, mysession
import sys

Login = Blueprint('Login', __name__)

posts = [{}]


@Login.route("/")
@Login.route("/home")
def home():
    #202212
    mysession["state"]="home or /"
    print(mysession)
    #202212
    role =  mysession["role"]
    print('role: '+ role)

    return render_template('home.html', posts=posts, role=role)


@Login.route("/about")
def about():
    #202212
    mysession["state"]="about"
    print(mysession)
    return render_template('about.html', title='About')


@Login.route("/login", methods=['GET', 'POST'])
def login():

    #202212
    mysession["state"]="login"
    print(mysession)
    role=None

    # jeg tror det her betyder at man er er logget på, men har redirected til login
    # så kald formen igen
    # men jeg forstår det ikke
    if current_user.is_authenticated:
        return redirect(url_for('Login.home'))

    
    form = CustomerLoginForm()

    # Først bekræft, at inputtet fra formen er gyldigt... (f.eks. ikke tomt)
    if form.validate_on_submit():

        

        #"202212"
        # her checkes noget som skulle være sessionsvariable, men som er en GET-parameter
        # implementeret af AL. Ideen er at teste på om det er et employee login
        # eller om det er et customer login.
        # betinget tildeling. Enten en employee - eller en customer instantieret
        # Skal muligvis laves om. Hvad hvis nu user ikke blir instantieret
        user = select_Investors(form.id.data)
    
        # Derefter tjek om hashet af adgangskoden passer med det fra databasen...
        # Her checkes om der er logget på
        if user != None and bcrypt.check_password_hash(user[1], form.password.data):

            mysession["role"] = roles[2] 
            mysession["id"] = form.id.data
            print(mysession)
            print(roles)

            login_user(user, remember=form.remember.data)
            flash('Login successful.','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('Login.home'))
        else:
            flash('Login Unsuccessful. Please check identifier and password', 'danger')
    #202212


    #202212
    role =  mysession["role"]
    print('role: '+ role)

    #return render_template('login.html', title='Login', is_employee=is_employee, form=form)
    return render_template('login.html', title='Login', is_employee=False, form=form, role=role   )
#teachers={{"id": str(1234), "name":"anders"},}
#data={"user_id": str(user_id), "total_trials":total_trials}

    #hvor gemmes login-bruger-id?

@Login.route("/logout")
def logout():
    #202212
    mysession["state"]="logout"
    print(mysession)

    logout_user()
    return redirect(url_for('Login.home'))

bank/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ current_user.name }}</h1>

    <div class="content-section">
      <p>Accounts:</p>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">account_number</th>
            <th scope="col">cpr_number</th>
            <th scope="col">name</th>
            <th scope="col">managed by</th>
          </tr>
        </thead>
        <tbody>
        {% for n in acc %}
          <tr>
            <th scope="row">{{n[3]}}</th>
            <td>{{n[2]}}</td>
            <td>{{n[1]}}</td>
            <td>{{n[0]}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>


    <h4><font color="tomato">Note: This page should  be accessible by customers and employees!</font></h4>
{% endblock content %}

bank/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">

            <h3>No Commissions, Tight Spreads </h3>
            <p>
              BlueChip Stock Trader allows you to trade stocks with zero comissions and tight spreads. 
            </p>
          </div>
{% endblock content %}

bank/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>BlueChip Stock Trader - {{ title }}</title>
    {% else %}
        <title>BlueChip Stock Trader</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">BlueChip Stock Trader</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('Login.home') }}">Home</a>
              <!-- Dropdown top right -->
              
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                

                <a class="nav-item nav-link" href="{{ url_for('Login.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('Login.login') }}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <!-- Right Side box-->
        <div class="col-md-4">
          <div class="content-section" >
            <h3>Account</h3>
              <ul class="list-group">
              {% if current_user.is_authenticated %}

			   
			        <p>Welcome back, {{ current_user[2] }}. </p><p> Your account balance is ${{ current_user[3] }} which you can use to buy even more stonks.  
              </p>
              <p>Remember that equities in the long run increase in value. To the moon!</p>
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Customer.trade') }}">Trade</a></li>
                <li class="list-group-item list-group-item-light"><a class="nav-item nav-link" href="{{ url_for('Customer.portfolio') }}">View portfolio</a></li>

              {% else %}
                <li class="list-group-item list-group-item-light">Please login in order to view account.</li>
              {% endif %}
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

bank/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.id.label(class="form-control-label") }}
                    {% if form.id.errors %}
                        {{ form.id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>


        </form>

    </div>



{% endblock content %}

bank/templates/portfolio.html
{% extends "layout.html" %}
{% block content %}
    
	

  <div class="content-section">	
    <h3>Portfolio:</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Ticker symbol</th>
          <th scope="col">Quantity</th>
          <th scope="col">Purchase price</th>
          <th scope="col">Current price</th>
          <th scope="col">Profit/Loss</th>
        </tr>
      </thead>
      <tbody>
      {% for n in inv %}
        <tr>
          <th scope="row">{{n[0]}}</th>
          <td>{{n[1]}} shares</td>
          <td>${{n[2]}}</td>
          <td>${{n[3]}}</td>
          <td>${{n[4]}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>  
  </div>

	
{% endblock content %}

bank/templates/trade.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <h3>Trade the market</h3>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Ticker symbol</th>
                <th scope="col">Current price</th>
              </tr>
            </thead>
            <tbody>
            {% for n in market_data %}
              <tr>
                <th scope="row"> 
                     {{n[0]}}</th>
                <td>${{n[1]}} </td>
                
            {% endfor %}
            </tbody>
          </table>  
    </div>

    <div class="content-section">
        <h3>Order entry</h3>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Ticker symbol</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
            <form method="POST" action="">
              <tr>
                <th scope="row"> 
                    {{ form.ticker(class="btn btn-outline-info") }}</th>
                <td> {{ form.quantity(class="btn btn-outline-info") }}</td>
                <td><div class="form-group">
                    {{ form.buy(class="btn btn-outline-info") }}
                </div> </td>
                <td><div class="form-group">
                    {{ form.sell(class="btn btn-outline-info") }}
                </div> </td>
            
            </tbody>
          </table> 
        </form>
    </div>
{% endblock content %}